import mongoose from 'mongoose';

const auctionInvoiceSchema = new mongoose.Schema({
  // Invoice Details
  invoiceNumber: {
    type: String,
    unique: true
    // Auto-generated by pre-save hook, no need for required: true
  },
  saleNumber: {
    type: Number
    // Auto-generated by pre-save hook, no need for required: true
  },
  invoiceDate: {
    type: Date,
    default: Date.now
  },

  // Auction & Lot Reference
  auction: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Auction',
    required: true
  },
  lotNumbers: [{
    type: Number,
    required: true
  }],

  // Buyer Details
  buyer: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  buyerDetails: {
    name: { type: String, required: true },
    email: String,
    phone: String,
    gstin: String,
    pan: String,
    buyerNumber: String,
    commissionPercentage: { type: Number, default: 12 } // For display only
  },

  // Billing Address
  billingAddress: {
    street: String,
    city: String,
    state: String,
    stateCode: String,
    zipCode: String
  },

  // Shipping Address
  shippingAddress: {
    street: String,
    city: String,
    state: String,
    stateCode: String,
    zipCode: String
  },

  // Lot/Product Details (Array for multiple lots)
  lots: [{
    lotNumber: { type: Number, required: true },
    description: { type: String, required: true },
    detailedDescription: String, // For delivery note
    hsnCode: { type: String, default: '97050090' },
    quantity: { type: Number, default: 1 },
    hammerPrice: { type: Number, required: true },
    commissionRate: { type: Number, default: 12 }, // Percentage (for display only)
    commissionAmount: { type: Number, default: 0 } // Calculated (for display only, not added to total)
  }],

  // Charges
  packingForwardingCharges: {
    amount: { type: Number, default: 0 },
    hsnCode: { type: String, default: '99854' }
  },

  insuranceCharges: {
    amount: { type: Number, default: 0 },
    hsnCode: { type: String, default: '99681' },
    declined: { type: Boolean, default: false }
  },

  // GST Calculation
  gst: {
    type: {
      type: String,
      enum: ['IGST', 'CGST+SGST'],
      required: true
    },
    rate: { type: Number, default: 5.00 }, // Percentage

    // For items (lot)
    itemGSTRate: { type: Number, default: 5.00 },
    itemGSTAmount: Number,

    // For packing & forwarding
    packingGSTRate: { type: Number, default: 18.00 },
    packingGSTAmount: Number,

    // Total GST
    totalGST: Number,

    // CGST & SGST (if applicable)
    cgst: { type: Number, default: 0 },
    sgst: { type: Number, default: 0 }
  },

  // Amount Summary
  amounts: {
    grossAmount: Number,
    totalGST: Number,
    totalCommission: { type: Number, default: 0 }, // For display only, not added to totalPayable
    roundOff: Number,
    totalPayable: Number
  },

  // Payment Status
  isPaid: {
    type: Boolean,
    default: false
  },
  paidAt: Date,
  paymentMode: String,

  // Customer Visibility
  sentToCustomer: {
    type: Boolean,
    default: false
  },
  sentToCustomerAt: Date,

  // Shipping Details
  shipping: {
    transportMode: String,
    vehicleNumber: String,
    dateOfSupply: Date,
    placeOfSupply: String
  },

  // Company Details (Chronicle Vaults)
  companyDetails: {
    name: { type: String, default: 'Chronicle Vaults' },
    gstin: String,
    pan: String,
    msme: String,
    address: String,
    city: String,
    state: String,
    stateCode: String,
    phone: String,
    email: String,
    bankDetails: {
      bankName: String,
      accountName: String,
      accountNumber: String,
      ifsc: String,
      branch: String
    }
  },

  // Status
  status: {
    type: String,
    enum: ['Draft', 'Generated', 'Sent', 'Paid', 'Cancelled'],
    default: 'Draft'
  },

  // Invoice Type
  invoiceType: {
    type: String,
    enum: ['Customer', 'Vendor', 'ASI'],
    default: 'Customer'
  },

  // Notes
  notes: String,
  termsAndConditions: String

}, {
  timestamps: true
});

// Note: Invoice number is now assigned by InvoiceNumberTracker
// This ensures sequential numbering and proper tracking of deleted numbers

// Calculate GST and amounts before saving
auctionInvoiceSchema.pre('save', function(next) {
  // Calculate commission for each lot (for display only)
  this.lots.forEach(lot => {
    lot.commissionAmount = (lot.hammerPrice * lot.commissionRate) / 100;
  });

  // Sum all hammer prices from all lots
  const totalHammerPrice = this.lots.reduce((sum, lot) => sum + (lot.hammerPrice || 0), 0);
  const packingCharges = this.packingForwardingCharges.amount;

  // Calculate total commission (for display only, not added to totalPayable)
  this.amounts.totalCommission = this.lots.reduce((sum, lot) => sum + (lot.commissionAmount || 0), 0);

  // Calculate item GST
  this.gst.itemGSTAmount = (totalHammerPrice * this.gst.itemGSTRate) / 100;

  // Calculate packing GST
  if (packingCharges > 0) {
    this.gst.packingGSTAmount = (packingCharges * this.gst.packingGSTRate) / 100;
  } else {
    this.gst.packingGSTAmount = 0;
  }

  // Total GST
  this.gst.totalGST = this.gst.itemGSTAmount + this.gst.packingGSTAmount;

  // If CGST+SGST, split equally
  if (this.gst.type === 'CGST+SGST') {
    this.gst.cgst = this.gst.totalGST / 2;
    this.gst.sgst = this.gst.totalGST / 2;
  }

  // Calculate amounts (commission is NOT added to totalPayable)
  this.amounts.grossAmount = totalHammerPrice + packingCharges;
  this.amounts.totalGST = this.gst.totalGST;

  const subtotal = this.amounts.grossAmount + this.amounts.totalGST;
  this.amounts.roundOff = Math.round(subtotal) - subtotal;
  this.amounts.totalPayable = Math.round(subtotal);

  next();
});

// Virtual for buyer state comparison
auctionInvoiceSchema.virtual('isInterstate').get(function() {
  return this.billingAddress.stateCode !== this.companyDetails.stateCode;
});

// Index for faster queries
auctionInvoiceSchema.index({ invoiceNumber: 1 });
auctionInvoiceSchema.index({ buyer: 1 });
auctionInvoiceSchema.index({ auction: 1, buyer: 1 }, { unique: true }); // One invoice per buyer per auction
auctionInvoiceSchema.index({ status: 1 });

export default mongoose.model('AuctionInvoice', auctionInvoiceSchema);
